# Generated by Django 6.0.4 on 2026-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
